create_db = "CREATE DATABASE mydatabase"
list_of_dbs = "SHOW DATABASES"
create_tbl = "CREATE TABLE customers (name VARCHAR(255), address VARCHAR(255))"
insert_customers_data = "INSERT INTO customers (name, address) VALUES ('sree', 'mumbai')"
select_all_customers = "select * from customers"
select_customer_by_name = "select * from customers where name =%s"